### ISSUE TITLE
Problem in Converting Jupyter notebook to pdf

### ISSUE THREAD

**Issue by Japrap** [jupyter/jupyter_core#144]
When I want to save Jupyter notebook as a pdf file, I receive the following error:

```
nbconvert failed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex
? 
! Emergency stop.
<*> .\notebook
              .tex
No pages of output.
Transcript written on ?.
```
Any idea how can I solve this problem?

**Comment by DevinCharles** [comment]
Me too...
```
nbconvert failed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex
? 
! Emergency stop.
<*> .\notebook
              .tex
No pages of output.
Transcript written on ?.
```

**Comment by DevinCharles** [comment]
I think I've got the solution... but I had a few things wrong, so here are the steps if anyone out there is following along.

From the command line I ran:
```
jupyter nbconvert --to pdf "full-path-to-notebook.ipynb"
```

This gave me an error that I had the wrong version of Pandoc installed: it needs to be less than 2.0.0. It's available from here:
[Pandoc 2.0.0](https://github.com/jgm/pandoc/releases?after=2.1.1)

Running nbconvert again, this time with latex output, I found:
```
Cannot find ec-lmtt10.mf
```
It turns out I was missing some font packages in latex, so I used *tlmgr* (for tex-live) to install these two packages:
```
lm
lm-math
```

However, attempting to convert to pdf from jupyter lab still gave the same error. I tracked down the offending line of code here:
*...\site-packages\nbconvert\exporters\pdf.py*
**Line 66**
```
#writer = Instance("nbconvert.writers.FilesWriter", args=(), kw={'build_directory': '.'})
writer = Instance("nbconvert.writers.FilesWriter", args=(), kw={'build_directory': ''})
```
Changing the `'build_directory' : '.'` to `'build_directory' : ''` solves the issue for me... apparently it was looking in the wrong location for the file, ie:
```
xelatex notebook.tex
```
Rather than:
```
xelatex .\notebook.tex
```

**Comment by TimGreenshaw** [comment]
I only needed to edit ...\site-packages\nbconvert\exporters\pdf.py as described above. That fixed the problem for my windows machine. (nbconvert works without the change on linux/mac.)

**Comment by takluyver** [comment]
If anyone needs to post follow-up issues, please see jupyter/nbconvert: https://github.com/jupyter/nbconvert.

**Comment by yuliaUU** [comment]
I get this error:
```
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
? 
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.
```

It was not clear for me what you did to avoid this mistake

**Comment by mufiye** [comment]
> I get this error:
> 
> ```
> nbconvert failed: PDF creating failed, captured latex output:
> Failed to run "xelatex .\notebook.tex -quiet" command:
> This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
>  restricted \write18 enabled.
> entering extended mode
> ! Undefined control sequence.
> <*> .\notebook
>               .tex -quiet
> ? 
> ! Emergency stop.
> <*> .\notebook
>               .tex -quiet
> No pages of output.
> Transcript written on ?.
> ```
> 
> It was not clear for me what you did to avoid this mistake

have you solved this problem？i have same error log as you.And I try the method above,but still can't solve this error.

**Comment by yinghuanli** [comment]
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
? 
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.

I have the same problem

**Comment by kevin-bates** [comment]
As Thomas noted above, this issue should be opened in the [nbconvert](https://github.com/jupyter/nbconvert) repository.  

Thank you.

**Comment by yinghuanli** [comment]
Could you please explain how can I contact people for help if I meet a problem when writing codes?
________________________________
发件人: Kevin Bates <notifications@github.com>
发送时间: 2020年11月10日 22:36
收件人: jupyter/jupyter_core <jupyter_core@noreply.github.com>
抄送: Li, Yinghuan <yinghuan.li.20@ucl.ac.uk>; Comment <comment@noreply.github.com>
主题: Re: [jupyter/jupyter_core] Problem in Converting Jupyter notebook to pdf (#144)


As Thomas noted above, this issue should be opened in the nbconvert<https://github.com/jupyter/nbconvert> repository.

Thank you.

―

**Comment by kevin-bates** [comment]
Hi @yinghuanli - I understand your frustration - the Jupyter ecosystem is quite large and entangled.

This particular repository is very small and specialized.  It primarily manages the various filesystem paths used by the various Jupyter applications.  It also provides the primary base class used by those Jupyter applications as well as the `jupyter` command itself - which knows how to locate the actual application being launched (e.g., `jupyter nbconvert`).  This is why its name is `jupyter_core`.

However, the actual code specific to the application being invoked - in this case, `nbconvert`- is maintained in other repositories by, most likely, a different set of maintainers.  As a result, the first "task" in determining how to contact people for help is identifying the appropriate repository relative to the issue encountered.  

In your case, you're trying to convert a notebook to PDF and your issue opens with `nbconvert failed` - so I forwarded you to that repository where, if you open an issue there, should find someone that can help you.  Had I had the authorization to transfer your issue to that repository, I'd have done that transfer for you.  Since that's not the case, that's something you'll need to do.

You might find this page on [jupyter.org](https://jupyter.org/) helpful: https://jupyter.org/documentation. It consists of links to various documentation pages, but it also organizes things in a way that might help in locating the desired repository since the GitHub repository can be found via the corresponding documentation.  For example, the link for nbconvert takes you here: https://nbconvert.readthedocs.io/en/latest/.

I'm sorry for your frustration.  Good luck.
