### ISSUE TITLE
Use of distutils triggers warning when setuptools (>=v49.2.0) is used in jupyter kernels

### ISSUE THREAD

**Issue by mstimberg** [jupyter/jupyter_core#193]
Since version v49.2.0, `setuptools` is raising a warning if it gets imported after `distutils`. Unfortunately, `jupyter_code` uses the `strtobool` function from `distutils` in https://github.com/jupyter/jupyter_core/blob/ed50a593d03684d93c0234372cd2947e500ef7b4/jupyter_core/paths.py#L397
which means that any jupyter notebook/console that imports `setuptools` (or a package that uses `setuptools`) will show this warning. This is very confusing, especially for beginners who often mistake this warning for an error. 

I don't think that `jupyter_core` is to blame here, but maybe it would be worth getting rid of this `distutil` use? It seems that this warning might only be around until the next release (see discussion in pypa/setuptools#2259), though, so it is rather a temporary issue that might go away soon.

**Comment by pganssle** [comment]
Regardless of the erroneous warning about the import order (which affects nothing), you should definitely remove all use of `distutils` that it is plausible to use. The erroneous warnings are only the first stage of a larger effort to deprecate and remove `distutils` itself. Replacements are not available for everything in `distutils`, but I doubt that we'll ever do anything except remove `strtobool`, since that's hardly in the core API of a build tool.

**Comment by MSeal** [comment]
There's not many people actively maintaining some of these libraries (I'm certainly stretched too thin), but I'd happily merge a change if someone could take the time to make the appropriate deprecation removals.
