### ISSUE TITLE
Jupyter_core conflicts with the Jupyter meta-pacjage: they install same file jupyter.py

### ISSUE THREAD

**Issue by yurivict** [jupyter/jupyter_core#405]
Jupyter_core conflicts with [jupyter 1.0.0](https://pypi.org/project/jupyter/).

Could you please remove jupyter.py ?

Thanks,
Yuri

**Comment by minrk** [comment]
The fix for this is to remove `jupyter.py` from the metapackage, which should truly be empty. The file needs to be in jupyter_core for `python3 -m jupyter` to work properly.

This has in fact already been done in https://github.com/jupyter/jupyter/pull/198. but there hasn't been a metapackage release since then. I'll work on that.

**Comment by minrk** [comment]
This is fixed by 1.1 of the Jupyter metapackage
