### ISSUE TITLE
What's the path for global nbextensions? Get confused about paths.

### ISSUE THREAD

**Issue by haobibo** [jupyter/jupyter_core#73]
@takluyver  @minrk

As far as I know, jupyter notebook find extensions from jupyter_data_dir(), which points to a user specific dir (like `/home/.local/share/jupyter`).

My questions is that: in some scenarios, for example, using JupyterHub (`https://github.com/jupyter/jupyterhub/issues/305`), users want a global path to install shared nbextensions for all users (I guess Python `Lib/site-packages` is not a good place to store extension data). But what's its officially recommended path (`jupyter_data_dir()` points to a user specific dir) ?

Besides, it seems confusing of current paths design: `jupyter_data_dir()`, `jupyter_config_dir()`, `jupyter_config_path()`, `jupyter_path()`. Can anyone fill below table to clarify where each kind of data are officially suggested to be stored?

|                                                                                 | user specific                      |     global (all users)       |
|-----------------------------------------------------------------|------------------------------------|--------------------------------|
| kernel profile (for Py2, Py3, R, Scala ...)             |  (May be not needed)      |                                         |
| extensions (server-side, front-side, templates) |                                             |                                         |
| runtime kernel session information                     |                                             |  (May be not needed)  |

BTW, I think it would be a nicer design if extensions/kernel profiles from both user-specific and global dirs to be loaded when a notebook server starts for a user.

**Comment by takluyver** [comment]
Kernel specs (which tell us how to start the kernel) and nbextensions are found in a search path of data directories described here, including both user and system directories:
http://jupyter.readthedocs.org/en/latest/system.html#data-files

Jupyter config files have a different search path, which also includes user and system locations:
http://jupyter.readthedocs.org/en/latest/system.html#configuration

The connection files, which hold the details of a specific running kernel process, live in a runtime directory which is only per-user - because the kernel process is running for one user:
http://jupyter.readthedocs.org/en/latest/system.html#runtime-files

The kernel may have its own config (e.g. IPython does in `~/.ipython`), but that's separate from Jupyter, and each kernel may do its own thing.
